#!/usr/bin/env bash

touch logfile.txt

list="$(ls $1)"
for i in $list; do
	$2 $i
	if [ $? -eq 0 ]; then
		echo "$2" "$i" ::::::: succeeded >> logfile.txt
	else
		echo "$2" "$i" ::::::: failed >> logfile.txt
	fi
done
