#!/usr/bin/env bash

touch logfile.txt						# Maak een logbestand aan
echo "Statussen van commando's: " > logfile.txt			# Leeg het logbestand
list="$(ls $1)"							# Maak een lijst bestaande uit alle bestanden in het meegegeven directory
for i in $list; do						# Loop door de lijst
	$2 $i							# Voer het meegegeven commando op alle elementen uit
	if [ $? -eq 0 ]; then					# Test of de exitcode gelijk is aan 0
		echo "$2" "$i" ::::::: succeeded >> logfile.txt	# Als dat zo is, is het commando succesvol uitgevoerd
	else
		echo "$2" "$i" ::::::: failed >> logfile.txt	# Anders is het commando mislukt.
	fi							# Eindig if-statement
done								# Eindig for-loop
