#!/usr/bin/env bash

touch $1.txt					# Maak bestand aan met meegegeven bestandsnaam
read -p "Gebruikersnaam: " username		# Vraag om de gebruikersnaam en sla deze op in $username
if [ "$username" = "" ]; then			# Als er niks is ingevoerd
	$username=$(whoami)			# Gebruik dan de huidige user
fi

while true; do								# Start oneindige while-loop
	read -s -t 15 -p "Wachtwoord:" curPassword			# Vraag om wachtwoord en plaats deze in $curPassword
	echo								# \n
	read -s -t 15 -p "Herhaal wachtwoord:" newPassword		# Vraag om wacthwoord te herhalen en sla het herhaalde wachtwoord op in $newPassword
	echo								# \n
	if [ "$newPassword" = "$curPassword" ]; then			# Als de ingevoerde wachtwoorden overeenkomen
		echo "$username" "$(echo -n "$newPassword" | md5sum)">> $1.txt	# Hash het wachtword en sla deze, samen met de gebruikersnaam, op in het aangemaakte bestand
		break							# Break uit de while-loop
	fi								# Eindig if statement
done									# Eindig loop

echo Hallo "$username"! Uw account is opgeslagen in het opgegeven bestand.
