#!/usr/bin/env bash

list="$(ls $1)"
length="$(find $1 -maxdepth 1 -type f -not -name 't_*' | wc -l)"
arr=($list)
rand=$(( ( RANDOM % $length ) + 1 ))
randomPos=${arr[$rand]}
for i in $list; do
	if [ "$i" = "$randomPos" ]; then
		display $1$i
		echo $1$i
	fi
done
